kind: pipeline
type: docker
name: deploy-hugo-to-s3

steps:
  - name: build-site
    image: klakegg/hugo:0.111.3
    commands:
      - hugo --minify --baseURL "https://restaurant-landingpage-leojet02.s3.us-east-1.amazonaws.com/"

  - name: upload-to-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: 
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY: 
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION:
        from_secret: s3_region
      BUCKET: 
        from_secret: s3_bucket_name
    commands:
      - aws s3 sync public/ s3://$BUCKET/ --delete