kind: pipeline
type: docker
name: deploy-hugo-to-s3

steps:
  - name: build-site
    image: klakegg/hugo:0.111.3
    commands:
      - hugo --minify --baseURL "https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/"

  - name: upload-to-s3
    image: amazon/aws-cli
    environment:
      BUCKET: restaurant-landingpage-leojet02
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync public/ s3://$BUCKET/ --acl public-read --delete
