kind: pipeline
type: docker
name: deploy-hugo-to-s3

steps:
  - name: build-site
    image: klakegg/hugo:0.111.3
    commands:
      - hugo --minify --baseURL "https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/"

  - name: upload-to-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_DEFAULT_REGION:
        from_secret: s3_region
      BUCKET:
        from_secret: s3_bucket_name
    commands:
      - aws s3 sync public/ s3://$BUCKET/ --delete

  - name: show-output
    image: alpine
    commands:
      - echo "✅ Site déployé sur: https://$BUCKET.s3.amazonaws.com/index.html"
      - echo "✅ GitHub Repo: https://github.com/${DRONE_REPO}"
